# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 15:45
from __future__ import unicode_literals

import backend.libs.media
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pro', '0005_auto_20161124_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250, null=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('profile', models.TextField(blank=True, null=True)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=backend.libs.media.generate_filename_job)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('street_number', models.CharField(blank=True, max_length=250, null=True)),
                ('route', models.CharField(blank=True, max_length=250, null=True)),
                ('locality', models.CharField(blank=True, max_length=250, null=True)),
                ('administrative_area_level_2', models.CharField(blank=True, max_length=250, null=True)),
                ('administrative_area_level_1', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro.Pro')),
            ],
        ),
    ]
