# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 16:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0003_contract_contracttime'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_time',
            field=models.ManyToManyField(to='datas.ContractTime'),
        ),
        migrations.AddField(
            model_name='job',
            name='contracts',
            field=models.ManyToManyField(to='datas.Contract'),
        ),
        migrations.AddField(
            model_name='job',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='job',
            name='video_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
