# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20161125_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, null=True)),
                ('nb', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['nb'],
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='contract_time',
            field=models.ManyToManyField(blank=True, to='datas.ContractTime'),
        ),
        migrations.AlterField(
            model_name='job',
            name='contracts',
            field=models.ManyToManyField(blank=True, to='datas.Contract'),
        ),
        migrations.AddField(
            model_name='jobquestion',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='job.Job'),
        ),
    ]
