# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 11:21
from __future__ import unicode_literals

import backend.libs.media
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_auto_20161019_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=backend.libs.media.generate_filename_user),
        ),
    ]
