# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 17:27
from __future__ import unicode_literals

import backend.libs.media
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='user/default.png', null=True, upload_to=backend.libs.media.generate_filename_user),
        ),
    ]
