# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250, null=True, verbose_name='Raison sociale')),
                ('web_site', models.CharField(blank=True, max_length=250, null=True, verbose_name='Site web')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
    ]
