# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_employes'),
        ('pro', '0002_pro_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='administrative_area_level_1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='administrative_area_level_2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='ca',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='cp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='employes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datas.Employes'),
        ),
        migrations.AddField(
            model_name='pro',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datas.Industry'),
        ),
        migrations.AddField(
            model_name='pro',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='locality',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='route',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='street_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pro',
            name='video_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
