# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_auto_20161024_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='image',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
    ]
