# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 11:21
from __future__ import unicode_literals

import backend.libs.media
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_pro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to=backend.libs.media.generate_filename_pro),
        ),
    ]
